DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Blogi CASCADE;
DROP TABLE IF EXISTS Postaus CASCADE;
DROP TABLE IF EXISTS Kategoria CASCADE;
DROP TABLE IF EXISTS PostauksenKategoria CASCADE;
